spring.application.name=KITT-Server

server.port=9000

spring.datasource.url=jdbc:sqlite:./data/KittServerDatabase.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

# Logging (Logback)
logging.level.com.adlph.transport.automotive.kitt=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.file.name=./log/KittServerLog.log
logging.logback.rollingpolicy.max-file-size=5KB
logging.logback.rollingpolicy.max-history=2